--EJ 1
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
CREATE TABLE EMPLEADOS(
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    ESPECIALIDAD VARCHAR2(50),
    EXPERIENCIA VARCHAR2(50),
    TIPO_EMPLEADO VARCHAR2(50),
    DNI_VETERINARIO CHAR(9)
);
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_DNI_VETERINARIO FOREIGN KEY(DNI_VETERINARIO) REFERENCES EMPLEADOS(DNI);

DROP TABLE CLIENTES CASCADE CONSTRAINTS;
CREATE TABLE CLIENTES(
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    TELEFONO INT,
    FORMA_PAGO VARCHAR2(50),
    DIRECCION VARCHAR2(50)
);
DROP TABLE MASCOTAS CASCADE CONSTRAINTS;
CREATE TABLE MASCOTAS(
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    SEXO VARCHAR2(50),
    COLOR VARCHAR2(50),
    TIPO VARCHAR2(50),
    RAZA VARCHAR2(50),
    FECHA_NACIMIENTO DATE,
    DNI_AUXILIAR_DATOSINI CHAR(9),
    FECHA_DATOSINI DATE,
    IMPORTE_DATOSINI INT
);
ALTER TABLE MASCOTAS ADD CONSTRAINT FK_DNIAUX FOREIGN KEY(DNI_AUXILIAR_DATOSINI) REFERENCES EMPLEADOS(DNI);

DROP TABLE CONSULTAS_PASADAS CASCADE CONSTRAINTS;
CREATE TABLE CONSULTAS_PASADAS(
    DNI_VETERINARIO CHAR(9),
    ID_MASCOTA INT,
    FECHA DATE,
    IMPORTE INT
);
ALTER TABLE CONSULTAS_PASADAS ADD CONSTRAINT FK_DNIVETERINARIO FOREIGN KEY(DNI_VETERINARIO) REFERENCES EMPLEADOS(DNI);
ALTER TABLE CONSULTAS_PASADAS ADD CONSTRAINT FK_IDMASCOTAS FOREIGN KEY(ID_MASCOTA) REFERENCES MASCOTAS(ID);
ALTER TABLE CONSULTAS_PASADAS ADD CONSTRAINT PK_CONSULTAS_PASADAS PRIMARY KEY(DNI_VETERINARIO,ID_MASCOTA);

DROP TABLE CLIENTES_Y_MASCOTAS CASCADE CONSTRAINTS;
CREATE TABLE CLIENTES_Y_MASCOTAS(
    DNI_CLIENTE CHAR(9),
    ID_MASCOTA INT
);
ALTER TABLE CLIENTES_Y_MASCOTAS ADD CONSTRAINT FK_DNICLIENTE FOREIGN KEY(DNI_CLIENTE) REFERENCES EMPLEADOS(DNI);
ALTER TABLE CLIENTES_Y_MASCOTAS ADD CONSTRAINT FK_IDMASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES MASCOTAS(ID);
ALTER TABLE CLIENTES_Y_MASCOTAS ADD CONSTRAINT PK_CLIENTES_Y_MASCOTAS PRIMARY KEY (DNI_CLIENTE,ID_MASCOTA);

--EJ 2
DROP TABLE CAMISETAS CASCADE CONSTRAINTS;
CREATE TABLE CAMISETAS(
    REFERENCIA INT PRIMARY KEY,
    TALLA VARCHAR2(50),
    NOMBRE_DISP VARCHAR2(50),
    TIPO_TEJIDO VARCHAR2(50),
    FORMA VARCHAR2(50),
    COLOR VARCHAR2(50),
    PRECIO NUMBER,
    ID_DISEÑO INT
);
ALTER TABLE CAMISETAS ADD CONSTRAINT FK_ID_DISEÑO FOREIGN KEY(ID_DISEÑO) REFERENCES DISEÑOS(ID);

DROP TABLE CLIENTES CASCADE CONSTRAINTS;
CREATE TABLE CLIENTES(
    EMAIL VARCHAR2(50) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CP VARCHAR2(50),
    NUM_COMPRAS INT
);

DROP TABLE DISEÑOS CASCADE CONSTRAINTS;
CREATE TABLE DISEÑOS(
    ID INT PRIMARY KEY
);

DROP TABLE PROVEEDORES CASCADE CONSTRAINTS;
CREATE TABLE PROVEEDORES(
    NIF INT PRIMARY KEY,
    DIRECCION VARCHAR2(50),
    NOMBRE_C VARCHAR2(50),
    CP VARCHAR2(50),
    LOCALIDAD VARCHAR2(50),
    TIPO VARCHAR2(50)
);

DROP TABLE PEDIDOS CASCADE CONSTRAINTS;
CREATE TABLE PEDIDOS(
    REFERENCIA INT PRIMARY KEY,
    IMPORTE NUMBER
);

DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
CREATE TABLE EMPLEADOS(
    DNI CHAR(9) PRIMARY KEY,
    APELLIDOS VARCHAR2(50),
    NOMBRE VARCHAR2(50),
    EDAD INT,
    ESDISENADOR VARCHAR2(50),
    ESVENDEDOR VARCHAR2(50)
);

DROP TABLE COMPRAS CASCADE CONSTRAINTS;
CREATE TABLE COMPRAS(
    REFERENCIA_CAMISETA INT,
    EMAIL_CLIENTE VARCHAR2(50)
);
ALTER TABLE COMPRAS ADD CONSTRAINT FK_REF FOREIGN KEY(REFERENCIA_CAMISETA) REFERENCES CAMISETAS(REFERENCIA);
ALTER TABLE COMPRAS ADD CONSTRAINT FK_EMAIL FOREIGN KEY(EMAIL_CLIENTE) REFERENCES CLIENTES(EMAIL);

