DROP TABLE FRANQUICIAS;
CREATE TABLE FRANQUICIAS(
    CODIGO INT,
    NOMBRE_FRANQUICIADO VARCHAR2(50),
    PROVINCIA VARCHAR2(50),
    LOCALIDAD VARCHAR2(50),
    FACTURACION NUMBER(8,2),
    TELEFONO CHAR(14),
    EMAIL VARCHAR2(50)
);

DROP TABLE EMPLEADOS;
CREATE TABLE EMPLEADOS(
    DNI CHAR(9),
    NOMBRE VARCHAR2(50),
    APELLIDOS VARCHAR2(50),
    FECHA_NACIMIENTO DATE,
    PUESTO VARCHAR2(50),
    COD_FRANQUICIA INT
);

--3
ALTER TABLE FRANQUICIAS ADD CONSTRAINT PK_COD PRIMARY KEY(CODIGO);
--4
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_DNI_EMP PRIMARY KEY(DNI);
ALTER TABLE EMPLEADOS ADD CONSTRAINT CHK_DNI_EMP CHECK(REGEXP_LIKE(DNI,'[0-9]{8},[A-Z]'));
--5
ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADO_FK_FRANQUICIA FOREIGN KEY(COD_FRANQUICIA) REFERENCES FRANQUICIAS(CODIGO);
--6
ALTER TABLE EMPLEADOS RENAME CONSTRAINT EMPLEADO_FK_FRANQUICIA TO FK_EMP_FRA;
--7
ALTER TABLE FRANQUICIAS RENAME TO FRANQUICIAS_NUEVAS;
--8
ALTER TABLE EMPLEADOS ADD SALARIO NUMBER(7,1);
ALTER TABLE EMPLEADOS ADD CHECK(SALARIO>=0);
--9
ALTER TABLE EMPLEADOS DROP CONSTRAINT PK_DNI_EMP;
--10
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_DNI_NOMBRE_EMPLEADOS PRIMARY KEY(DNI,NOMBRE);
--11
ALTER TABLE EMPLEADOS ADD DNI_JEFE CHAR(9);
ALTER TABLE EMPLEADOS ADD NOMBRE_JEFE VARCHAR2(100);
--12
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_COMPUESTA_EMPLEADOS FOREIGN KEY(DNI_JEFE,NOMBRE_JEFE) REFERENCES EMPLEADOS(DNI,NOMBRE);
