DROP TABLE ESTADIOS;
CREATE TABLE ESTADIOS(
    NOMBRE VARCHAR2(50),
    CAPACIDAD NUMBER(6,2),
    DIRECCION VARCHAR2(50),
    LOCALIDAD VARCHAR2(50),
    COMPARTIDO VARCHAR(5)
);
ALTER TABLE ESTADIOS ADD CONSTRAINT PK_NOMBRE PRIMARY KEY(NOMBRE);


DROP TABLE CLUBES;
CREATE TABLE CLUBES(
    REFERENCIA CHAR(5),
    NOMBRE VARCHAR2(50),
    ANO_FUNDACION INT,
    NOMBRE_ESTADIO VARCHAR2(50)
);
ALTER TABLE CLUBES ADD CONSTRAINT PK_REFERENCIA PRIMARY KEY(REFERENCIA);


DROP TABLE TRABAJADORES;
CREATE TABLE TRABAJADORES(
    DNI CHAR(9),
    NOMBRE VARCHAR2(50),
    APELLIDOS VARCHAR2(100),
    REF_CLUB CHAR(5),
    APODO_JUGADOR VARCHAR2(50),
    DORSAL_JUGADOR INT,
    FECHA_NACIMIENTO_JUGADOR DATE,
    TIPOTRABAJADOR VARCHAR2(50),
    ESAUXILIAR CHAR(2),
    ESFISIO CHAR(2)
);
ALTER TABLE TRABAJADORES ADD CONSTRAINT PK_DNI PRIMARY KEY(DNI);

DROP TABLE PARTIDOS;
CREATE TABLE PARTIDOS(
    ID INT,
    CLUB_LOCAL CHAR(5),
    CLUB_VISITANTE CHAR(5),
    RESULTADO CHAR(5)
);
ALTER TABLE PARTIDOS ADD CONSTRAINT PK_ID PRIMARY KEY(ID);


DROP TABLE DISPUTAS_PARTIDO_JUGADOR;
CREATE TABLE DISPUTAS_PARTIDO_JUGADOR(
    ID_PARTIDO INT,
    DNI_EMPLEADO_JUGADOR CHAR(9),
    MINUTOS INT
);
ALTER TABLE DISPUTAS_PARTIDO_JUGADOR ADD CONSTRAINT PK_DISPUTAS_PARTIDO_JUGADOR PRIMARY KEY(ID_PARTIDO,DNI_EMPLEADO_JUGADOR);


DROP TABLE JUECES;
CREATE TABLE JUECES(
    ID INT,
    FEDERACION VARCHAR2(50),
    NOMBRE VARCHAR2(50),
    APELLIDOS VARCHAR2(100),
    FECHA_NACIMIENTO DATE
);
ALTER TABLE JUECES ADD CONSTRAINT PK_IDJUECES PRIMARY KEY(ID);

DROP TABLE JUECES_PARTIDOS;
CREATE TABLE JUECES_PARTIDOS(
    ID_JUEZ INT,
    ID_PARTIDO INT
);
ALTER TABLE JUECES_PARTIDOS ADD CONSTRAINT PK_JUECES_PARTIDOS PRIMARY KEY(ID_JUEZ,ID_PARTIDO);

--A
ALTER TABLE CLUBES ADD CONSTRAINT FK_NOMBRE_ESTADIO FOREIGN KEY(NOMBRE_ESTADIO) REFERENCES ESTADIOS;
--B
ALTER TABLE TRABAJADORES ADD CONSTRAINT FK_REF_CLUB FOREIGN KEY(REF_CLUB) REFERENCES CLUBES;
--C
ALTER TABLE PARTIDOS ADD CONSTRAINT FK_CLUB_LOCAL FOREIGN KEY(CLUB_LOCAL) REFERENCES CLUBES;
--D
ALTER TABLE PARTIDOS ADD CONSTRAINT FK_CLUB_VISITANTE FOREIGN KEY(CLUB_VISITANTE) REFERENCES CLUBES;
--E
ALTER TABLE DISPUTAS_PARTIDO_JUGADOR ADD CONSTRAINT FK_ID_PARTIDO FOREIGN KEY(ID_PARTIDO) REFERENCES PARTIDOS;
--F
ALTER TABLE DISPUTAS_PARTIDO_JUGADOR ADD CONSTRAINT FK_DNI_EMPLEADO_JUGADOR FOREIGN KEY(DNI_EMPLEADO_JUGADOR) REFERENCES TRABAJADORES;
--G
ALTER TABLE JUECES_PARTIDOS ADD CONSTRAINT FK_ID_JUEZ FOREIGN KEY(ID_JUEZ) REFERENCES JUECES;
--H
ALTER TABLE JUECES_PARTIDOS ADD CONSTRAINT FK_ID_PARTIDO_JUECES_PARTIDOS FOREIGN KEY(ID_JUEZ) REFERENCES PARTIDOS;

--4
ALTER TABLE CLUBES ADD NOMBRE_PRESIDENTE INT;
--5
ALTER TABLE CLUBES MODIFY NOMBRE_PRESIDENTE CHAR(9);
--6
ALTER TABLE CLUBES RENAME COLUMN NOMBRE_PRESIDENTE TO DNI_PRESIDENTE;
--7
ALTER TABLE CLUBES ADD CONSTRAINT FK_DNI_PRESIDENTE_CLUB FOREIGN KEY(DNI_PRESIDENTE) REFERENCES TRABAJADORES;
--8
ALTER TABLE CLUBES RENAME CONSTRAINT FK_DNI_PRESIDENTE_CLUB TO FK_DNI_PRESI_CLUB;
--9
ALTER TABLE CLUBES DROP CONSTRAINT FK_DNI_PRESI_CLUB;
--10
ALTER TABLE CLUBES DROP COLUMN DNI_PRESIDENTE;
ALTER TABLE CLUBES RENAME TO EQUIPOS;



