-- CREAR TABLA
CREATE TABLE CCAAS(
    NOMBRE VARCHAR2(50),
    POBLACION INT,
    SUPERFICIE NUMBER(7,2)
);
-- PARA MODIFICAR LA TABLA/AÑADIR
ALTER TABLE CCAAS ADD LOCALIDAD VARCHAR2(100); 
-- PARA BORRAR LA TABLA
DROP TABLE CCAAS;
--PARA RENOMBRAR UNA COLUMNA
ALTER TABLE CCAAS RENAME COLUMN SUPERFICIE TO SUPERF;
-- PARA BORRAR UNA COLUNMA
ALTER TABLE CCAAS DROP COLUMN NOMBRE;
-- PARA BORRAR UNA TABLA Y TODAS SUS RESTRICCIONES DE LAS QUE DEPENDA (PK Y FK) SE USA CASCADE CONSTRAINTS
DROP TABLE ALUMNOS CASCADE CONSTRAINTS SYS_C008321 ;

-- 06/11/2024
--  PDF 1 INTRODUCCIÓN
-- EJ 1
DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS (
    NOMBRE VARCHAR2(15),
    APELLIDOS VARCHAR2(50),
    DNI CHAR(9)
); 
--EJ 2
ALTER TABLE ALUMNOS ADD CP NUMBER(5);
--EJ 3
ALTER TABLE ALUMNOS ADD FEC_NAC DATE;
--EJ 4
ALTER TABLE ALUMNOS DROP COLUMN CP;
ALTER TABLE ALUMNOS RENAME COLUMN FEC_NAC TO F_NAC;
ALTER TABLE ALUMNOS MODIFY APELLIDOS VARCHAR2(200);
--EJ 5
    --5.1
    CREATE TABLE ALUMNOS1 (
        NOMBRE VARCHAR2(15),
        APELLIDOS VARCHAR2(50),
        DNI CHAR(9) PRIMARY KEY
    ); 
    --5.2
    CREATE TABLE ALUMNOS2 (
        NOMBRE VARCHAR2(15),
        APELLIDOS VARCHAR2(50),
        DNI CHAR(9)
    ); 
    ALTER TABLE ALUMNOS2 ADD PRIMARY KEY (DNI) ;
    --5.3
    CREATE TABLE ALUMNOS3 (
        NOMBRE VARCHAR2(15),
        APELLIDOS VARCHAR2(50),
        DNI CHAR(9)
    ); 
    ALTER TABLE ALUMNOS3 ADD CONSTRAINT PKDNIALUMNOS3 PRIMARY KEY(DNI) ;
    --5.4
    CREATE TABLE ALUMNOS4 (
        NOMBRE VARCHAR2(15),
        APELLIDOS VARCHAR2(50),
        DNI CHAR(9),
        PRIMARY KEY (DNI)        
    ); 
    
--EJ 6
DROP TABLE LOCALIDADES;
CREATE TABLE LOCALIDADES (
        ID INT ,
        LOCALIDAD VARCHAR2(100)        
); 
ALTER TABLE LOCALIDADES ADD PRIMARY KEY (ID) ;
ALTER TABLE ALUMNOS ADD ID_LOCALIDAD INT; 
ALTER TABLE ALUMNOS ADD FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID);

--PDF 2 AMPLIACIÓN DE TABLAS 



